export type QueryParam = {
  q?: string;
  body?: string;
  title?: string;
  url?: string;
  tagged?: string;
  nottagged?: string;
  answers?: string;
  views?: string;
  user?: string;
  page?: string;
  pagesize?: string;
  accepted?: string;
  closed?: string;
  migrated?: string;
  wiki?: string;
  notice?: string;
  order?: string;
  sort?: string;
  min?: string;
  max?: string;
  fromdate?: string;
  todate?: string;
};

export type PageLessQueryParam = {
  q?: string;
  body?: string;
  title?: string;
  url?: string;
  tagged?: string;
  nottagged?: string;
  answers?: string;
  views?: string;
  user?: string;
  accepted?: string;
  closed?: string;
  migrated?: string;
  wiki?: string;
  notice?: string;
  order?: string;
  sort?: string;
  min?: string;
  max?: string;
  fromdate?: string;
  todate?: string;
};
