export type QueryParam = {
  q: string;
  body: string;
  title: string;
  url: string;
  tagged: string;
  nottagged: string;
  answers: number | null | undefined;
  views: number | null | undefined;
  user: number | null | undefined;
  page: number | null | undefined;
  pagesize: number | null | undefined;
  accepted: boolean | null | undefined;
  closed: boolean | null | undefined;
  migrated: boolean | null | undefined;
  wiki: boolean | null | undefined;
  notice: boolean | null | undefined;
  order: 'desc' | 'asc';
  sort: 'activity' | 'creation' | 'votes' | 'relevance';
  min: number | null | undefined;
  max: number | null | undefined;
  fromdate: number | null | undefined;
  todate: number | null | undefined;
};
